Changed syntax, added bundler, better arg system

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,3 +1,31 @@
-#! /bin/sh
+#!/bin/sh
 
-cp hello.fn ~/hello.fn
+check_makedeps()
+{
+    echo "Checking makedeps"
+
+    gcc_includes=$(stat /bin/gcc)
+    make_includes=$(stat /bin/make)
+
+    if [ "$gcc_includes" == 1 ]; then
+        echo "gcc not found, cannot build Fusion"
+        echo "Install gcc to install"
+        
+        exit 1
+    fi
+
+    echo "gcc is installed"
+
+    if [ "$make_includes" == 1 ]; then
+        echo "make not found, cannot build Fusion"
+        echo "Install make to install"
+
+        exit 1
+    fi
+
+    echo "make is installed"
+}
+
+check_makedeps
+
+cp .hello.fn ~/.hello.fn
